### PR TITLE
Some examples on how to use and make sense of the Performance Counter Monitor

### PR DESCRIPTION
**Pull request by betatim**
The examples are pretty basic in what they do in the hope that simple
examples will allow you to understand what PCM is telling you. Then use PCM
on more difficult problems where it is not (as) clear what is going on.

### CODE REVIEW

**Comment by betatim** [comment]
@kdungs and @GerhardRaven, can one of you take a look at this and then merge it? I think having a second person do the merge is a good idea in general. Plus it means my commits get treated like everyone else's.

**Comment by betatim** [comment]
Too slow in fixing things up it seems. Need to learn how to use git to undo my commit that was "too late", then pull in @kdungs changes, then re-apply my changes (using foreach).

Also a lesson in the need to coordinate when two people are trying to push things to the same branch :-s

**Comment by kdungs** [comment]
Doesn't git do this automatically when you `pull --rebase`?
Also: I'm sorry, I should have assigned myself to the issues before fixing them.

**Comment by GerhardRaven** [comment]
On May 31, 2014, at 12:36:27, Tim Head notifications@github.com wrote:

> Too slow in fixing things up it seems. Need to learn how to use git to undo my commit that was "too late", then pull in @kdungs changes, then re-apply my changes (using foreach).
> 
> Also a lesson in the need to coordinate when two people are trying to push things to the same branch :-s

Basically, don’t ;-) 
Develop on your own branch, and when you’re happy, and it’s ready for public consumption, then merge 
it into the ‘release’ or ‘head’ or whatever the canonical branch is. And if someone wants to track
you while you’re still developing, tell them your own little development branch. In Git, branching is
easy & cheap, and merging as well. So use the tool as intended ;-)

— Gerhard

**Comment by kdungs** [comment]
I think this is what @betatim intended to do, only I pushed to his development branch... :/

**Comment by betatim** [comment]
Gerhard, tell that to @kdungs ;) I naively assumed no one would be adding commits to "my" PR and that is how I ended up in this mess.

Anywho, anymore for anymore or merge?

ps. I will investigate --rebase. Though the recommendation is to do `git fetch` and then `git merge $branch` instead of having `pull` do it for you.

**Comment by GerhardRaven** [comment]
On May 31, 2014, at 12:45:25, Kevin Dungs notifications@github.com wrote:

> I think this is what @betatim intended to do, only I pushed to his development branch... :/

OK, in that case, all bets are off ;-)

— Gerhard

**Comment by kdungs** [comment]
> Anywho, anymore for anymore or merge?

I wasn't able to actually test the binaries (due to old-MacBook-syndrome) but up to that point, I have no further concerns.

**Comment by GerhardRaven** [comment]
On May 31, 2014, at 12:47:34, Tim Head notifications@github.com wrote:

> Gerhard, tell that to @kdungs ;) I naively assumed no one would be adding commits to “my" PR and that is how I ended up in this mess.

OK ;-)
I think the nominal workflow I’ll pick up is to ‘pull’ into my local repository, develop there
on a branch (and then I’m in full control ;-) and then ‘push’ once I’m ready…

— Gerhard

**Comment by betatim** [comment]
@kdungs so press the big tempting green button that says "merge pull request" already.

**Pull request merged**
